# Generated by Django 4.1.3 on 2022-12-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('pembuat_event', models.CharField(max_length=200)),
                ('tanggal_pendaftaran', models.DateField()),
                ('tanggal_penyisihan_1', models.DateField(blank=True, null=True)),
                ('tanggal_penyisihan_2', models.DateField(blank=True, null=True)),
                ('tanggal_penyisihan_3', models.DateField(blank=True, null=True)),
                ('tanggal_semifinal', models.DateField(blank=True, null=True)),
                ('tanggal_final', models.DateField(blank=True, null=True)),
                ('pengumuman_pemenang', models.DateField(blank=True, null=True)),
                ('tingkat_event', models.CharField(choices=[(None, 'Pilih Tingkat Event'), ('Desa', 'Desa/Kelurahan'), ('Kecamatan', 'Kecamatan'), ('Kabupaten', 'Kabupaten'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=30)),
                ('pelaksanaan', models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online')], max_length=30)),
                ('berjenjang', models.CharField(choices=[(None, 'Apakah Lomba Berjenjang?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=50)),
                ('anggaran_biaya', models.FloatField()),
                ('upload_brosur', models.FileField(blank=True, null=True, upload_to='proposal/brosur', verbose_name='Upload Brosur Lomba')),
                ('upload_udangan', models.FileField(blank=True, null=True, upload_to='proposal/undangan', verbose_name='Upload Undangan Lomba')),
                ('upload_file', models.FileField(help_text='Format file dalam bentuk .pdf', upload_to='proposal', verbose_name='Upload File Proposal')),
                ('Catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ekskul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekskul.extracurricular')),
                ('penanggungjawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.teacher')),
                ('santri', models.ManyToManyField(blank=True, help_text='Pada PC/Laptop, tekan Ctrl untuk memilih banyak opsi', to='ekskul.student', verbose_name='Santri yang ikut')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wakasek', models.CharField(choices=[('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Pending', 'Menunggu respon')], default='Pending', max_length=30)),
                ('is_kepsek', models.CharField(choices=[('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Pending', 'Menunggu respon')], default='Pending', max_length=30)),
                ('is_bendahara', models.CharField(choices=[('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Pending', 'Menunggu respon')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
    ]
