# Generated by Django 4.1.3 on 2022-12-21 16:34

from django.db import migrations, models
import django.db.models.deletion
import proposal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalUstadz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('pembuat_event', models.CharField(max_length=200)),
                ('tanggal_awal_pelaksanaan', models.DateField()),
                ('tanggal_akhir_pelaksanaan', models.DateField()),
                ('tingkat_event', models.CharField(choices=[(None, 'Pilih Tingkat Event'), ('Desa', 'Desa/Kelurahan'), ('Kecamatan', 'Kecamatan'), ('Kabupaten', 'Kabupaten'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=30)),
                ('pelaksanaan', models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online')], max_length=30)),
                ('berjenjang', models.CharField(choices=[(None, 'Apakah Lomba Berjenjang?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=50)),
                ('anggaran_biaya', models.FloatField()),
                ('upload_file', models.FileField(upload_to=proposal.models.proposal_directory_path, verbose_name='Upload File Proposal')),
                ('ustadz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Proposal',
            },
        ),
        migrations.CreateModel(
            name='ProposalSantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('pembuat_event', models.CharField(max_length=200)),
                ('tanggal_awal', models.DateField(verbose_name='tanggal_awal_pelaksanaan')),
                ('tanggal_akhir', models.DateField(verbose_name='tanggal_akhir_pelaksanaan')),
                ('tingkat_event', models.CharField(choices=[(None, 'Pilih Tingkat Event'), ('Desa', 'Desa/Kelurahan'), ('Kecamatan', 'Kecamatan'), ('Kabupaten', 'Kabupaten'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Internasional', 'Internasional')], max_length=30)),
                ('pelaksanaan', models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online')], max_length=30)),
                ('berjenjang', models.CharField(choices=[(None, 'Apakah Lomba Berjenjang?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=50)),
                ('anggaran_biaya', models.FloatField()),
                ('upload_file', models.FileField(upload_to=proposal.models.proposal_directory_path, verbose_name='Upload File Proposal')),
                ('ekskul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekskul.extracurricular', verbose_name='ekskul_yang_terlibat')),
                ('penanggungjawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.teacher')),
                ('santri', models.ManyToManyField(to='ekskul.student', verbose_name='santri yang terlibat')),
            ],
            options={
                'verbose_name': 'Student Proposal',
            },
        ),
    ]
