# Generated by Django 4.0.6 on 2023-01-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalstatusbendahara',
            name='bukti_transfer',
            field=models.ImageField(blank=True, null=True, upload_to='proposal/transfer'),
        ),
        migrations.AddField(
            model_name='proposalstatusbendahara',
            name='catatan_bendahara',
            field=models.TextField(default='Aman', max_length=200),
        ),
    ]
