# Generated by Django 4.1.3 on 2022-12-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0004_alter_teacher_nama'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal_Santri',
            new_name='ProposalSantri',
        ),
        migrations.RenameModel(
            old_name='Proposal_Ustadz',
            new_name='ProposalUstadz',
        ),
        migrations.AlterModelOptions(
            name='proposalsantri',
            options={'verbose_name': 'Student Proposals'},
        ),
        migrations.AlterModelOptions(
            name='proposalustadz',
            options={'verbose_name': 'Teacher Proposals'},
        ),
    ]
