# Generated by Django 4.0.6 on 2023-01-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_batas_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='catatan_bendahara',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
