# Generated by Django 4.1.3 on 2022-12-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_rename_proposal_santri_proposalsantri_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalsantri',
            options={'verbose_name': 'Student Proposal'},
        ),
        migrations.AlterModelOptions(
            name='proposalustadz',
            options={'verbose_name': 'Teacher Proposal'},
        ),
    ]
