# Generated by Django 4.1.3 on 2022-12-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_proposal_lokasi_acara_1_proposal_lokasi_acara_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='lokasi_acara_1',
            new_name='lokasi_event',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='lokasi_acara_2',
            new_name='provinsi_event',
        ),
    ]
