# Generated by Django 4.0.6 on 2023-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_proposalstatusbendahara_catatan_bendahara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(blank=True, default='2022-12-29', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pelaksanaan',
            field=models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='catatan_bendahara',
            field=models.TextField(default='Aman', max_length=200),
        ),
    ]
