# Generated by Django 4.1.3 on 2022-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_rename_lokasi_acara_1_proposal_lokasi_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='provinsi_event',
            new_name='provinsi',
        ),
        migrations.AddField(
            model_name='proposal',
            name='kota',
            field=models.CharField(default='', max_length=200, verbose_name='Kota/Kabupaten'),
        ),
    ]
