# Generated by Django 4.0.6 on 2023-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_alter_proposal_batas_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(blank=True, null=True),
        ),
    ]
