# Generated by Django 4.0.6 on 2023-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_alter_proposal_batas_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='nama_bank',
            field=models.CharField(default='Muamalat', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='nomor_rekening',
            field=models.CharField(default='3410015776', max_length=100),
        ),
    ]
