# Generated by Django 4.1.3 on 2022-12-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_rename_provinsi_event_proposal_provinsi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='upload_udangan',
            new_name='upload_undangan',
        ),
    ]
