# Generated by Django 4.1.3 on 2022-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_rename_upload_udangan_proposal_upload_undangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstatus',
            name='slug',
            field=models.SlugField(default='Wakasek', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalstatusbendahara',
            name='slug',
            field=models.SlugField(default='Bendahara', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalstatuskepsek',
            name='slug',
            field=models.SlugField(default='Kepsek', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='is_wakasek',
            field=models.CharField(choices=[('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Pending', 'Menunggu respon'), ('Some Info Required', 'Kami membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Wakasek Ekskul'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='is_bendahara',
            field=models.CharField(choices=[('Accepted', 'Diterima'), ('Pending', 'Menunggu respon'), ('Some Info Required', 'Kami membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Bendahara'),
        ),
        migrations.AlterField(
            model_name='proposalstatuskepsek',
            name='is_kepsek',
            field=models.CharField(choices=[('Accepted', 'Diterima'), ('Rejected', 'Ditolak'), ('Pending', 'Menunggu respon'), ('Some Info Required', 'Kami membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Kepala Sekolah'),
        ),
    ]
