# Generated by Django 4.0.6 on 2023-01-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0002_alter_extracurricular_logo'),
        ('proposal', '0006_proposal_nama_bank_proposal_nomor_rekening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalInventaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_proposal', models.CharField(max_length=200, verbose_name='Judul Proposal Pengadaan')),
                ('tanggal_pembelian', models.DateField(blank=True, null=True, verbose_name='Rencana tanggal pembelian')),
                ('nama_toko', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_toko', models.CharField(blank=True, max_length=200, null=True)),
                ('nomor_rekening', models.CharField(default='', max_length=100)),
                ('nama_bank', models.CharField(default='Muamalat', max_length=100)),
                ('anggaran_biaya', models.FloatField()),
                ('upload_file', models.FileField(help_text='Format file dalam bentuk .pdf', upload_to='proposal', verbose_name='Upload File Proposal')),
                ('Catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ekskul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekskul.extracurricular', verbose_name='Keperluan untuk ekskul')),
                ('penanggungjawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.teacher')),
                ('santri', models.ManyToManyField(blank=True, help_text='Pada PC/Laptop, tekan Ctrl untuk memilih banyak opsi', to='ekskul.studentorganization', verbose_name='Keperluan untuk santri atas nama')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalInventarisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wakasek', models.CharField(choices=[('Accepted', 'Menerima'), ('Rejected', 'Menolak'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Wakasek Ekskul')),
                ('alasan_wakasek', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='Wakasek', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalinventaris')),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='nomor_rekening',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProposalInventarisStatusKepsek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kepsek', models.CharField(choices=[('Accepted', 'Menerima'), ('Rejected', 'Menolak'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Kepala Sekolah')),
                ('alasan_kepsek', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='Kepsek', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalinventaris')),
                ('status_wakasek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalinventarisstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalInventarisStatusBendahara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bendahara', models.CharField(choices=[('Accepted', 'Menerima'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Bendahara')),
                ('alasan_bendahara', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='Bendahara', max_length=20)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='proposal/transfer')),
                ('catatan_bendahara', models.TextField(default='Aman', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalinventaris')),
                ('status_kepsek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalinventarisstatuskepsek')),
            ],
        ),
    ]
