# Generated by Django 4.0.6 on 2023-02-02 16:53

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_proposalinventaris_proposalinventarisstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='bukti_transfer',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
        migrations.AlterField(
            model_name='proposalstatuskepsek',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
    ]
