# Generated by Django 4.1.3 on 2022-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_proposalstatus_slug_proposalstatusbendahara_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='is_wakasek',
            field=models.CharField(choices=[('Accepted', 'Menerima'), ('Rejected', 'Menolak'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Wakasek Ekskul'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='is_bendahara',
            field=models.CharField(choices=[('Accepted', 'Menerima'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Bendahara'),
        ),
        migrations.AlterField(
            model_name='proposalstatuskepsek',
            name='is_kepsek',
            field=models.CharField(choices=[('Accepted', 'Menerima'), ('Rejected', 'Menolak'), ('Pending', 'Menunda'), ('Some Info Required', 'Membutuhkan informasi lebih detail')], default='Pending', max_length=100, verbose_name='Keputusan Kepala Sekolah'),
        ),
    ]
