# Generated by Django 4.1.3 on 2023-07-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0006_extracurricular_ekskul_extr_id_e325fa_idx_and_more'),
        ('proposal', '0008_alter_proposalstatus_foto_alasan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='batas_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='berjenjang',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='pengumuman_pemenang',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tanggal_penyisihan_1',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tanggal_penyisihan_2',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tanggal_penyisihan_3',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tanggal_semifinal',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='nomor_rekening',
            field=models.CharField(default='', max_length=100, verbose_name='Nomor Rekening PJ'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pelaksanaan',
            field=models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=30, verbose_name='Tempat Pelaksanaan'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='santri',
            field=models.ManyToManyField(blank=True, help_text='Pada PC/Laptop, tekan Ctrl untuk memilih banyak opsi', to='ekskul.student', verbose_name='Santri yang terlibat'),
        ),
        migrations.AlterField(
            model_name='proposalinventaris',
            name='santri',
            field=models.ManyToManyField(blank=True, help_text='Pada PC/Laptop, tekan Ctrl untuk memilih banyak opsi', to='ekskul.student', verbose_name='Keperluan untuk santri atas nama'),
        ),
    ]
