# Generated by Django 4.1.3 on 2023-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_alter_proposalstatus_is_wakasek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(default='2022-12-29'),
        ),
        migrations.AddField(
            model_name='proposalstatusbendahara',
            name='bukti_transfer',
            field=models.ImageField(blank=True, null=True, upload_to='proposal/transfer'),
        ),
        migrations.AddField(
            model_name='proposalstatusbendahara',
            name='catatan_bendahara',
            field=models.TextField(default='Aman', max_length=200),
        ),
    ]
