# Generated by Django 4.1.3 on 2023-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_proposal_batas_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(blank=True, default='2022-12-29', null=True),
        ),
    ]
