# Generated by Django 4.1.3 on 2023-07-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_remove_proposal_batas_pendaftaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='upload_brosur',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='upload_undangan',
        ),
    ]
