# Generated by Django 4.1.3 on 2023-07-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0010_remove_proposal_upload_brosur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='tanggal_final',
            new_name='tanggal_pelaksanaan',
        ),
    ]
