# Generated by Django 4.1.3 on 2023-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0010_alter_proposal_batas_pendaftaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='pelaksanaan',
            field=models.CharField(choices=[(None, 'Pilih Jenis Pelaksanaan'), ('Offline', 'Offline'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
    ]
