# Generated by Django 4.1.3 on 2023-01-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0011_alter_proposal_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='batas_pendaftaran',
            field=models.DateField(blank=True, null=True),
        ),
    ]
