# Generated by Django 4.1.3 on 2023-02-08 16:56

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_proposalinventaris_proposalinventarisstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/koreksi'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/koreksi'),
        ),
        migrations.AlterField(
            model_name='proposalstatuskepsek',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/koreksi'),
        ),
    ]
