# Generated by Django 4.1.3 on 2023-07-12 14:02

from django.db import migrations, models
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0015_alter_proposalstatus_foto_alasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='nomor_rekening',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='bukti_transfer',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
        migrations.AlterField(
            model_name='proposalstatusbendahara',
            name='foto_alasan',
            field=models.ImageField(blank=True, null=True, upload_to='proposal/koreksi'),
        ),
        migrations.AlterField(
            model_name='proposalstatuskepsek',
            name='foto_alasan',
            field=ekskul.compress_image.CompressedImageField(blank=True, help_text='Format file harus .jpeg atau .jpg', null=True, quality=50, upload_to='proposal/transfer'),
        ),
    ]
