# Generated by Django 4.1.3 on 2022-12-09 06:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('no_hp', models.IntegerField(blank=True, default=0)),
                ('foto', models.ImageField(default='blank-profile.png', upload_to='user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jadwal', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=15)),
                ('waktu', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('niy', models.IntegerField(default=0)),
                ('gelar_depan', models.CharField(blank=True, max_length=20)),
                ('gelar_belakang', models.CharField(blank=True, max_length=20)),
                ('jabatan', models.CharField(blank=True, max_length=20)),
                ('jabatan_khusus', models.CharField(blank=True, max_length=50)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.IntegerField(unique=True)),
                ('nisn', models.IntegerField(unique=True)),
                ('kelas', models.CharField(choices=[('X-MIPA-A', 'X-MIPA-A'), ('X-MIPA-B', 'X-MIPA-B'), ('X-MIPA-C', 'X-MIPA-C'), ('X-MIPA-D', 'X-MIPA-D'), ('X-MIPA-E', 'X-MIPA-E'), ('X-MIPA-F', 'X-MIPA-F'), ('X-MIPA-G', 'X-MIPA-G'), ('X-MIPA-H', 'X-MIPA-H'), ('XI-MIPA-A', 'XI-MIPA-A'), ('XI-MIPA-B', 'XI-MIPA-B'), ('XI-MIPA-C', 'XI-MIPA-C'), ('XI-MIPA-D', 'XI-MIPA-D'), ('XI-MIPA-E', 'XI-MIPA-E'), ('XI-MIPA-F', 'XI-MIPA-F'), ('XI-MIPA-G', 'XI-MIPA-G'), ('XI-MIPA-H', 'XI-MIPA-H'), ('XII-MIPA-A', 'XII-MIPA-A'), ('XII-MIPA-B', 'XII-MIPA-B'), ('XII-MIPA-C', 'XII-MIPA-C'), ('XII-MIPA-D', 'XII-MIPA-D'), ('XII-MIPA-E', 'XII-MIPA-E'), ('XII-MIPA-F', 'XII-MIPA-F'), ('XII-MIPA-G', 'XII-MIPA-G'), ('XII-MIPA-H', 'XII-MIPA-H')], max_length=15)),
                ('ekskul', models.ManyToManyField(to='ekskul.extracurricular')),
            ],
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='pembina',
            field=models.ManyToManyField(to='ekskul.teacher'),
        ),
    ]
