# Generated by Django 4.0.6 on 2022-12-29 14:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Ekskul')),
                ('jadwal', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=15, verbose_name='Jadwal Pembinaan')),
                ('waktu', models.CharField(choices=[('Sore', 'Sore'), ('Malam', 'Malam'), ('Pagi', 'Pagi'), ('Siang', 'Siang')], max_length=15)),
                ('jadwal_tambahan', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], default='Tidak ada', max_length=20)),
                ('waktu_tambahan', models.CharField(blank=True, choices=[('Sore', 'Sore'), ('Malam', 'Malam'), ('Pagi', 'Pagi'), ('Siang', 'Siang')], max_length=15)),
                ('tipe', models.CharField(blank=True, choices=[('Ekskul', 'Ekstrakurikuler'), ('SC', 'Study Club')], max_length=20)),
                ('slug', models.SlugField(blank=True)),
                ('logo', models.ImageField(blank=True, default='no-image.png', null=True, upload_to='user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.IntegerField(unique=True)),
                ('nisn', models.CharField(max_length=20)),
                ('kelas', models.CharField(choices=[('X-MIPA-A', 'X-A'), ('X-MIPA-B', 'X-B'), ('X-MIPA-C', 'X-C'), ('X-MIPA-D', 'X-D'), ('X-MIPA-E', 'X-E'), ('X-MIPA-F', 'X-F'), ('X-MIPA-G', 'X-G'), ('X-MIPA-H', 'X-H'), ('XI-MIPA-A', 'XI-A'), ('XI-MIPA-B', 'XI-B'), ('XI-MIPA-C', 'XI-C'), ('XI-MIPA-D', 'XI-D'), ('XI-MIPA-E', 'XI-E'), ('XI-MIPA-F', 'XI-F'), ('XI-MIPA-G', 'XI-G'), ('XI-MIPA-H', 'XI-H'), ('XII-MIPA-A', 'XII-A'), ('XII-MIPA-B', 'XII-B'), ('XII-MIPA-C', 'XII-C'), ('XII-MIPA-D', 'XII-D'), ('XII-MIPA-E', 'XII-E'), ('XII-MIPA-F', 'XII-F'), ('XII-MIPA-G', 'XII-G'), ('XII-MIPA-H', 'XII-H')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='Nama Pembina')),
                ('niy', models.IntegerField(default=0, verbose_name='NIY')),
                ('gelar_depan', models.CharField(blank=True, max_length=20)),
                ('gelar_belakang', models.CharField(blank=True, max_length=20)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('jabatan_khusus', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('no_hp', models.IntegerField(blank=True, default=0)),
                ('foto', models.ImageField(blank=True, default='blank-profile.png', null=True, upload_to='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekskul_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.extracurricular')),
                ('nama_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.student')),
            ],
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='pembina',
            field=models.ManyToManyField(to='ekskul.teacher'),
        ),
    ]
