# Generated by Django 4.1.3 on 2022-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='jadwal_tambahan',
            field=models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], default='Tidak ada', max_length=20),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='tipe',
            field=models.CharField(blank=True, choices=[('Ekskul', 'Ekstrakurikuler'), ('SC', 'Study Club')], max_length=20),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='waktu_tambahan',
            field=models.TimeField(auto_now=True),
        ),
    ]
