# Generated by Django 4.1.3 on 2022-11-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=models.ImageField(default='blank-profile.png', upload_to='media'),
        ),
    ]
