# Generated by Django 4.1.3 on 2022-12-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0002_extracurricular_jadwal_tambahan_extracurricular_tipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='waktu',
            field=models.CharField(choices=[('Sore', 'Sore'), ('Malam', 'Malam'), ('Pagi', 'Pagi'), ('Siang', 'Siang')], max_length=15),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='waktu_tambahan',
            field=models.CharField(blank=True, choices=[('Sore', 'Sore'), ('Malam', 'Malam'), ('Pagi', 'Pagi'), ('Siang', 'Siang')], max_length=15),
        ),
    ]
