# Generated by Django 4.0.6 on 2023-02-02 16:16

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0002_alter_extracurricular_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='blank-profile.png', help_text='format foto .jpg / .jpeg', null=True, quality=50, upload_to='user'),
        ),
    ]
