# Generated by Django 4.1.3 on 2023-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0002_alter_extracurricular_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentorganization',
            name='nama_siswa',
        ),
        migrations.AddField(
            model_name='studentorganization',
            name='nama_siswa',
            field=models.ManyToManyField(to='ekskul.student'),
        ),
    ]
