# Generated by Django 4.0.6 on 2023-02-02 16:53

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0003_alter_teacher_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='logo',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='no-image.png', help_text='format logo .jpg / .jpeg', null=True, quality=50, upload_to='ekskul/logo'),
        ),
    ]
