# Generated by Django 4.1.3 on 2022-12-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0003_alter_extracurricular_waktu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
