# Generated by Django 4.1.3 on 2022-12-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0004_alter_teacher_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ekskul',
        ),
        migrations.CreateModel(
            name='StudentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.extracurricular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.student')),
            ],
        ),
    ]
