# Generated by Django 4.1.3 on 2023-01-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0005_remove_studentorganization_nama_siswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentorganization',
            name='nama_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.student'),
        ),
    ]
