# Generated by Django 4.0.6 on 2023-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0005_rename_nama_extracurricular_nama_ekskul_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extracurricular',
            index=models.Index(fields=['id', 'slug'], name='ekskul_extr_id_e325fa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nis', 'id'], name='ekskul_stud_nis_f5cc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['id', 'niy'], name='ekskul_teac_id_fef09c_idx'),
        ),
    ]
