# Generated by Django 4.1.3 on 2022-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0005_remove_student_ekskul_studentorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
