# Generated by Django 4.1.3 on 2022-12-12 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0006_extracurricular_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='jadwal',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=15, verbose_name='Jadwal Pembinaan'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama Ekskul'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='nisn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nama_lengkap',
            field=models.CharField(max_length=100, verbose_name='Nama Pembina'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='niy',
            field=models.IntegerField(default=0, verbose_name='NIY'),
        ),
    ]
