# Generated by Django 4.1.3 on 2023-02-02 15:41

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0007_alter_teacher_nama_lengkap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='blank-profile.png', null=True, quality=70, upload_to='user'),
        ),
    ]
