# Generated by Django 4.1.3 on 2022-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0008_alter_student_nis_alter_student_nisn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nisn',
            field=models.CharField(max_length=20),
        ),
    ]
