# Generated by Django 4.1.3 on 2023-02-02 15:48

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0008_alter_teacher_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='blank-profile.png', null=True, quality=50, upload_to='user'),
        ),
    ]
