# Generated by Django 4.1.3 on 2022-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0009_alter_student_nisn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_hp',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='no_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
