# Generated by Django 4.1.3 on 2023-02-08 16:56

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0010_alter_teacher_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='logo',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='no-image.png', null=True, quality=70, upload_to='ekskul/logo'),
        ),
    ]
