# Generated by Django 4.1.3 on 2023-07-12 14:02

from django.db import migrations, models
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0011_alter_extracurricular_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='logo',
            field=ekskul.compress_image.CompressedImageField(blank=True, default='no-image.png', help_text='format logo .jpg / .jpeg', null=True, quality=50, upload_to='ekskul/logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nama_lengkap',
            field=models.CharField(max_length=100, verbose_name='Nama Pembina'),
        ),
    ]
