# Generated by Django 4.0.6 on 2022-12-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembinaan', models.DateField()),
                ('catatan_pembinaan', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kehadiran_santri', models.ManyToManyField(to='ekskul.studentorganization')),
                ('nama_ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.extracurricular')),
                ('pembina_ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_absensi', models.ImageField(default='no-image.png', upload_to='ekskul/laporan')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laporan.report')),
            ],
        ),
    ]
