# Generated by Django 4.0.6 on 2023-02-02 16:53

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='foto_absensi',
            field=ekskul.compress_image.CompressedImageField(default='no-image.png', help_text='Format foto harus .jpg atau .jpeg', quality=50, upload_to='ekskul/laporan'),
        ),
    ]
