# Generated by Django 4.1.3 on 2022-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0006_extracurricular_slug'),
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='kehadiran_santri',
            field=models.ManyToManyField(to='ekskul.studentorganization'),
        ),
    ]
