# Generated by Django 4.1.3 on 2023-07-25 15:04

from django.db import migrations
import ekskul.compress_image


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_alter_uploadimage_foto_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='foto',
            field=ekskul.compress_image.CompressedImageField(default='no-image.png', help_text='Format foto .jpg atau .jpeg', quality=50, upload_to='ekskul/laporan'),
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
