# Generated by Django 4.1.3 on 2022-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_alter_report_kehadiran_santri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='foto_absensi',
            field=models.ImageField(upload_to='ekskul/laporan'),
        ),
    ]
