# Generated by Django 4.1.3 on 2022-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_alter_uploadimage_foto_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='foto_absensi',
            field=models.ImageField(default='no-image.png', upload_to='ekskul/laporan'),
        ),
    ]
