# Generated by Django 4.1.3 on 2022-12-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penilaian',
            options={'verbose_name': 'Penilaian Santri'},
        ),
    ]
