# Generated by Django 4.1.3 on 2022-12-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0002_alter_penilaian_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penilaian',
            options={'verbose_name': 'Penilaian', 'verbose_name_plural': 'Penilaian'},
        ),
    ]
