# Generated by Django 4.1.3 on 2022-12-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0011_rename_ekskul_studentorganization_ekskul_siswa_and_more'),
        ('nilai', '0003_alter_penilaian_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='nama_ekskul',
        ),
        migrations.RemoveField(
            model_name='penilaian',
            name='nama_siswa',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekskul.studentorganization'),
        ),
    ]
