# Generated by Django 4.1.3 on 2022-12-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekskul', '0011_rename_ekskul_studentorganization_ekskul_siswa_and_more'),
        ('nilai', '0004_remove_penilaian_nama_ekskul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskul.studentorganization'),
        ),
    ]
