# Generated by Django 4.0.6 on 2022-12-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeskripsiHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=250)),
                ('url', models.CharField(default='not-available', max_length=100)),
                ('color', models.CharField(default='primary', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeskripsiEkskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aplikasi', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=200)),
                ('url', models.CharField(default='ekskul:data-index', max_length=100)),
                ('color', models.CharField(default='primary', max_length=50)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deskripsi.deskripsihome')),
            ],
        ),
    ]
