# Generated by Django 4.1.3 on 2023-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskripsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskripsiekskul',
            name='icon',
            field=models.CharField(default='bi bi-file-earmark-text', max_length=50),
        ),
        migrations.AlterField(
            model_name='deskripsiekskul',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deskripsiekskul',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
