# Generated by Django 4.1.3 on 2023-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskripsi', '0002_deskripsiekskul_icon_alter_deskripsiekskul_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskripsiekskul',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
