# Generated by Django 4.1.3 on 2022-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskripsi', '0002_deskripsiekskul_color_deskripsiekskul_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskripsiekskul',
            name='url',
            field=models.CharField(default='ekskul:data-index', max_length=100),
        ),
    ]
