# Generated by Django 4.1.3 on 2022-12-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deskripsi', '0003_alter_deskripsiekskul_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskripsiekskul',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deskripsi.deskripsihome'),
        ),
    ]
