# Generated by Django 4.1.3 on 2022-12-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekskul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('hibah', models.CharField(choices=[(None, 'Apakah ini barang hibah?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=30)),
                ('pemberi_hibah', models.CharField(blank=True, max_length=100)),
                ('tanggal_hibah', models.DateField(blank=True)),
                ('tanggal_dibeli', models.DateField(blank=True)),
                ('anggaran_dana', models.FloatField(blank=True)),
                ('nama_toko', models.CharField(blank=True, max_length=100)),
                ('alamat_toko', models.TextField(blank=True, max_length=250)),
                ('pemilik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekskul.extracurricular')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_nota', models.FileField(default='blank-nota.png', upload_to='inventaris/nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang'), ('Dipinjam', 'Dipinjam')], max_length=100)),
                ('peminjam', models.CharField(blank=True, max_length=200)),
                ('keterangan', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Status',
                'verbose_name_plural': 'Inventory Status',
            },
        ),
    ]
