# Generated by Django 4.1.3 on 2022-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_Status',
            new_name='InventoryStatus',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='inventorystatus',
            options={'verbose_name': 'Inventory Status', 'verbose_name_plural': 'Inventory Status'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='hibah',
            field=models.CharField(choices=[(None, 'Apakah ini barang hibah?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Ya', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='anggaran_dana',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tanggal_dibeli',
            field=models.DateField(blank=True),
        ),
    ]
