# Generated by Django 4.1.3 on 2023-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tanggal_dibeli',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tanggal_hibah',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorystatus',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang'), ('Dipinjam', 'Dipinjam')], default='Tersedia', max_length=100),
        ),
    ]
