# Generated by Django 4.1.3 on 2022-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_rename_inventory_status_inventorystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='hibah',
            field=models.CharField(choices=[(None, 'Apakah ini barang hibah?'), ('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=30),
        ),
    ]
