# Generated by Django 4.1.3 on 2022-12-11 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0003_alter_inventory_hibah'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pemberi_hibah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tanggal_hibah',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
