# Generated by Django 4.1.3 on 2022-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_inventory_pemberi_hibah_inventory_tanggal_hibah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tanggal_hibah',
            field=models.DateField(blank=True),
        ),
    ]
