# Generated by Django 4.1.3 on 2022-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0006_alter_invoice_foto_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='foto_nota',
            field=models.FileField(default='blank-nota.png', upload_to='inventaris/nota'),
        ),
    ]
