# Generated by Django 4.1.3 on 2022-12-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('jenis_lomba', models.CharField(max_length=100)),
                ('tingkat_lomba', models.CharField(max_length=100)),
                ('tahun_lomba', models.DateField()),
                ('nama_lomba', models.CharField(max_length=100)),
                ('Penyelenggara_lomba', models.CharField(max_length=100)),
                ('peraih_prestasi', models.CharField(max_length=100)),
                ('sekolah', models.CharField(default='SMAS IT AL Binaa', max_length=100)),
                ('bidang_lomba', models.CharField(max_length=100)),
                ('kategori_kemenangan', models.CharField(max_length=100)),
                ('dokumentasi', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DokumentasiPrestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prestasi')),
                ('prestasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestasi.prestasi')),
            ],
        ),
    ]
