# Generated by Django 4.1.3 on 2022-12-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='sertifikat_1',
            field=models.ImageField(blank=True, null=True, upload_to='prestasi/sertifikat'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='sertifikat_2',
            field=models.ImageField(blank=True, null=True, upload_to='prestasi/sertifikat'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='dokumentasi',
            field=models.BooleanField(choices=[(1, 'Ada'), (0, 'Tidak Ada')]),
        ),
    ]
