# Generated by Django 4.0.6 on 2023-01-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0002_prestasi_sertifikat_1_prestasi_sertifikat_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='sekolah',
            field=models.CharField(default='SMAS IT Al Binaa', max_length=100),
        ),
    ]
