# Generated by Django 4.1.3 on 2023-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0003_alter_prestasi_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='foto',
            field=models.ImageField(blank=True, default='no-image.png', null=True, upload_to='prestasi'),
        ),
    ]
