# Generated by Django 4.0.6 on 2023-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0003_alter_prestasi_sekolah'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentasiprestasi',
            name='created_at',
            field=models.DateTimeField(default='2023-01-19'),
        ),
        migrations.AddField(
            model_name='dokumentasiprestasi',
            name='updated_at',
            field=models.DateTimeField(default='2023-01-19'),
        ),
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='foto',
            field=models.ImageField(blank=True, default='no-image.png', null=True, upload_to='prestasi'),
        ),
    ]
