# Generated by Django 4.0.6 on 2023-01-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0004_dokumentasiprestasi_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
