# Generated by Django 4.1.3 on 2023-01-19 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0004_alter_dokumentasiprestasi_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentasiprestasi',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 1, 20)),
        ),
        migrations.AddField(
            model_name='dokumentasiprestasi',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date(2023, 1, 20)),
        ),
    ]
