# Generated by Django 4.1.3 on 2023-01-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0005_dokumentasiprestasi_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='created_at',
            field=models.DateTimeField(default='2023-01-19'),
        ),
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='updated_at',
            field=models.DateTimeField(default='2023-01-19'),
        ),
    ]
