# Generated by Django 4.0.6 on 2023-01-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0005_alter_dokumentasiprestasi_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='dokumentasi',
            field=models.BooleanField(choices=[(1, 'Ada'), (0, 'Tidak Ada')], default=0),
        ),
    ]
