# Generated by Django 4.1.3 on 2023-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0006_alter_dokumentasiprestasi_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='dokumentasi',
            field=models.BooleanField(choices=[(1, 'Ada'), (0, 'Tidak Ada')], default=0),
        ),
    ]
