# Generated by Django 4.0.6 on 2023-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0006_alter_prestasi_dokumentasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentasiprestasi',
            name='foto',
            field=models.FileField(blank=True, default='no-image.png', null=True, upload_to='prestasi'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='sertifikat_1',
            field=models.FileField(blank=True, null=True, upload_to='prestasi/sertifikat'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='sertifikat_2',
            field=models.FileField(blank=True, null=True, upload_to='prestasi/sertifikat'),
        ),
    ]
