# Generated by Django 4.0.6 on 2023-06-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestasi', '0007_alter_dokumentasiprestasi_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='kelas_peraih_prestasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
